### ISSUE TITLE
Auto sass for Docker

### ISSUE THREAD

**Issue by TheRealFakeAdmin** [CosmoQuestX/CSB7.0#110]
The `sass --watch csb-themes/default/sass/style.scss:csb-themes/default/style.css` command should be run automatically when using docker to make the setup process easier.

**Comment by TheRealFakeAdmin** [comment]
@eladavron Here are working changes for the docker-compose setup.

I've noticed that the style container takes longer to close than the others, is this an optimal solution or do you have a better idea?

_Note that I changed some folder layouts._
[docker.zip](https://github.com/CosmoQuestX/CSB7.0/files/9343949/docker.zip)

**Comment by eladavron** [comment]
First of all, you're using `image` twice - you don't need it `docker-compose.yml` if it's also in your Dockerfile, so:
```yaml
style:
    build:
      context: .
      dockerfile: .docker/node/Dockerfile
    command: sass --watch /app/csb/csb-themes/default/sass/style.scss:/app/csb/csb-themes/default/style.css
    volumes:
      - .:/app
```
should suffice.
Also, while the command as you supplied it will work - it's not very scalable.
Consider instead putting it in a shell script and having your Dockerfile use that as an entrypoint.
That way you can modify the script to match your needs in the future.
If you upload your changes to a side branch I can help you make the changes there.
